Document: cpp2dot
Title: Debian cpp2dot Manual
Author: <insert document author here>
Abstract: This manual describes what cpp2dot is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cpp2dot/cpp2dot.sgml.gz

Format: postscript
Files: /usr/share/doc/cpp2dot/cpp2dot.ps.gz

Format: text
Files: /usr/share/doc/cpp2dot/cpp2dot.text.gz

Format: HTML
Index: /usr/share/doc/cpp2dot/html/index.html
Files: /usr/share/doc/cpp2dot/html/*.html
